# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
## - task: CmdLine@2
##   inputs:
##     script: 'sudo gem install cocoapods; pod install;'
# - task: Cache@2
#   inputs:
#     key: 'pods | "$(Agent.OS)" | Podfile.lock'
#     path: 'Pods'
#     cacheHitVar: 'PODS_CACHE_RESTORED'
# - task: CocoaPods@0
#   displayName: 'pod install using the CocoaPods task with defaults'
#   condition: ne(variables.PODS_CACHE_RESTORED, 'true')

- task: Cache@2
  inputs:
    key: 'example | pods | "$(Agent.OS)" | Podfile'
    path: 'Pods'
    cacheHitVar: 'PODS_CACHE_RESTORED'

# - script: |
#     #sudo gem install cocoapods-binary
#     xcode-select -print-path
#     sudo xcode-select -switch 'ShearShare.app'
#     xcode-select -print-path
        
- task: CocoaPods@0
  displayName: 'pod install using the CocoaPods task with defaults'
  condition: ne(variables.PODS_CACHE_RESTORED, 'true')

# - script: |
#     pod update
#   displayName: 'pod update'

- task: Xcode@5
  inputs:
    actions: 'build'
    destinationTypeOption: devices
    configuration: 'Beta'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/*.xcworkspace'
    packageApp: false

# - script: |
#     echo $(system.defaultworkingdirectory)
#     sudo apt install -y wget
#     sudo wget https://github.com/firebase/firebase-tools/releases/download/v11.0.1/firebase-tools-linux
#     sudo chmod +x ./firebase-tools-linux
#     ./firebase-tools-linux appdistribution:distribute $(system.defaultworkingdirectory)/release/ShearShare-Beta.ipa --app $(APP_ID) --groups $(TEST_GROUP_ID) --token "$(FIREBASE_TOKEN)" --release-notes-file ReleaseNotes.txt
#   displayName: 'Firebase Upload'
